// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(parquet_swiftFFI)
import parquet_swiftFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_parquet_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_parquet_swift_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureParquetSwiftInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt8: FfiConverterPrimitive {
    typealias FfiType = Int8
    typealias SwiftType = Int8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt16: FfiConverterPrimitive {
    typealias FfiType = Int16
    typealias SwiftType = Int16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int16, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol ReaderHandleProtocol: AnyObject, Sendable {
    
    func close() 
    
    func readRow() throws  -> [ColumnValue]?
    
    func schema() throws  -> [FieldSchema]
    
}
open class ReaderHandle: ReaderHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_parquet_swift_fn_clone_readerhandle(self.handle, $0) }
    }
public convenience init(path: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeParquetError_lift) {
    uniffi_parquet_swift_fn_constructor_readerhandle_new(
        FfiConverterString.lower(path),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_parquet_swift_fn_free_readerhandle(handle, $0) }
    }

    
    /**
     * Opens the file projecting only the specified root-level columns.
     *
     * `columns` is a list of column names to include.  Names not present in
     * the file are silently ignored.  The `schema()` of the returned handle
     * reflects the projected columns only.
     */
public static func newProjected(path: String, columns: [String])throws  -> ReaderHandle  {
    return try  FfiConverterTypeReaderHandle_lift(try rustCallWithError(FfiConverterTypeParquetError_lift) {
    uniffi_parquet_swift_fn_constructor_readerhandle_new_projected(
        FfiConverterString.lower(path),
        FfiConverterSequenceString.lower(columns),$0
    )
})
}
    

    
open func close()  {try! rustCall() {
    uniffi_parquet_swift_fn_method_readerhandle_close(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func readRow()throws  -> [ColumnValue]?  {
    return try  FfiConverterOptionSequenceTypeColumnValue.lift(try rustCallWithError(FfiConverterTypeParquetError_lift) {
    uniffi_parquet_swift_fn_method_readerhandle_read_row(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func schema()throws  -> [FieldSchema]  {
    return try  FfiConverterSequenceTypeFieldSchema.lift(try rustCallWithError(FfiConverterTypeParquetError_lift) {
    uniffi_parquet_swift_fn_method_readerhandle_schema(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReaderHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ReaderHandle

    public static func lift(_ handle: UInt64) throws -> ReaderHandle {
        return ReaderHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ReaderHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReaderHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ReaderHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReaderHandle_lift(_ handle: UInt64) throws -> ReaderHandle {
    return try FfiConverterTypeReaderHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReaderHandle_lower(_ value: ReaderHandle) -> UInt64 {
    return FfiConverterTypeReaderHandle.lower(value)
}






public protocol WriterHandleProtocol: AnyObject, Sendable {
    
    func appendRow(values: [ColumnValue]) throws 
    
    func close() throws 
    
}
open class WriterHandle: WriterHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_parquet_swift_fn_clone_writerhandle(self.handle, $0) }
    }
public convenience init(path: String, schema: [FieldSchema], config: WriterConfig)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeParquetError_lift) {
    uniffi_parquet_swift_fn_constructor_writerhandle_new(
        FfiConverterString.lower(path),
        FfiConverterSequenceTypeFieldSchema.lower(schema),
        FfiConverterTypeWriterConfig_lower(config),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_parquet_swift_fn_free_writerhandle(handle, $0) }
    }

    

    
open func appendRow(values: [ColumnValue])throws   {try rustCallWithError(FfiConverterTypeParquetError_lift) {
    uniffi_parquet_swift_fn_method_writerhandle_append_row(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeColumnValue.lower(values),$0
    )
}
}
    
open func close()throws   {try rustCallWithError(FfiConverterTypeParquetError_lift) {
    uniffi_parquet_swift_fn_method_writerhandle_close(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWriterHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = WriterHandle

    public static func lift(_ handle: UInt64) throws -> WriterHandle {
        return WriterHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: WriterHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WriterHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: WriterHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWriterHandle_lift(_ handle: UInt64) throws -> WriterHandle {
    return try FfiConverterTypeWriterHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWriterHandle_lower(_ value: WriterHandle) -> UInt64 {
    return FfiConverterTypeWriterHandle.lower(value)
}




public struct ColumnConfig: Equatable, Hashable {
    public var columnName: String
    public var compression: Compression?
    public var encoding: Encoding?
    public var enableDictionary: Bool?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(columnName: String, compression: Compression?, encoding: Encoding?, enableDictionary: Bool?) {
        self.columnName = columnName
        self.compression = compression
        self.encoding = encoding
        self.enableDictionary = enableDictionary
    }

    

    
}

#if compiler(>=6)
extension ColumnConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeColumnConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ColumnConfig {
        return
            try ColumnConfig(
                columnName: FfiConverterString.read(from: &buf), 
                compression: FfiConverterOptionTypeCompression.read(from: &buf), 
                encoding: FfiConverterOptionTypeEncoding.read(from: &buf), 
                enableDictionary: FfiConverterOptionBool.read(from: &buf)
        )
    }

    public static func write(_ value: ColumnConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.columnName, into: &buf)
        FfiConverterOptionTypeCompression.write(value.compression, into: &buf)
        FfiConverterOptionTypeEncoding.write(value.encoding, into: &buf)
        FfiConverterOptionBool.write(value.enableDictionary, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColumnConfig_lift(_ buf: RustBuffer) throws -> ColumnConfig {
    return try FfiConverterTypeColumnConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColumnConfig_lower(_ value: ColumnConfig) -> RustBuffer {
    return FfiConverterTypeColumnConfig.lower(value)
}


public struct WriterConfig: Equatable, Hashable {
    public var compression: Compression
    public var rowGroupSize: UInt32
    public var dataPageSize: UInt32
    public var enableDictionary: Bool
    public var enableStatistics: Bool
    public var columnConfigs: [ColumnConfig]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(compression: Compression, rowGroupSize: UInt32, dataPageSize: UInt32, enableDictionary: Bool, enableStatistics: Bool, columnConfigs: [ColumnConfig]) {
        self.compression = compression
        self.rowGroupSize = rowGroupSize
        self.dataPageSize = dataPageSize
        self.enableDictionary = enableDictionary
        self.enableStatistics = enableStatistics
        self.columnConfigs = columnConfigs
    }

    

    
}

#if compiler(>=6)
extension WriterConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWriterConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WriterConfig {
        return
            try WriterConfig(
                compression: FfiConverterTypeCompression.read(from: &buf), 
                rowGroupSize: FfiConverterUInt32.read(from: &buf), 
                dataPageSize: FfiConverterUInt32.read(from: &buf), 
                enableDictionary: FfiConverterBool.read(from: &buf), 
                enableStatistics: FfiConverterBool.read(from: &buf), 
                columnConfigs: FfiConverterSequenceTypeColumnConfig.read(from: &buf)
        )
    }

    public static func write(_ value: WriterConfig, into buf: inout [UInt8]) {
        FfiConverterTypeCompression.write(value.compression, into: &buf)
        FfiConverterUInt32.write(value.rowGroupSize, into: &buf)
        FfiConverterUInt32.write(value.dataPageSize, into: &buf)
        FfiConverterBool.write(value.enableDictionary, into: &buf)
        FfiConverterBool.write(value.enableStatistics, into: &buf)
        FfiConverterSequenceTypeColumnConfig.write(value.columnConfigs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWriterConfig_lift(_ buf: RustBuffer) throws -> WriterConfig {
    return try FfiConverterTypeWriterConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWriterConfig_lower(_ value: WriterConfig) -> RustBuffer {
    return FfiConverterTypeWriterConfig.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ColumnValue: Equatable, Hashable {
    
    case null
    case bool(v: Bool
    )
    case int8(v: Int8
    )
    case int16(v: Int16
    )
    case int32(v: Int32
    )
    case int64(v: Int64
    )
    case uInt8(v: UInt8
    )
    case uInt16(v: UInt16
    )
    case uInt32(v: UInt32
    )
    case uInt64(v: UInt64
    )
    case float16(v: Float
    )
    case float32(v: Float
    )
    case float64(v: Double
    )
    case bytes(v: Data
    )
    case utf8(v: String
    )
    case list(items: [ColumnValue]
    )
    case `struct`(fields: [ColumnValue]
    )





}

#if compiler(>=6)
extension ColumnValue: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeColumnValue: FfiConverterRustBuffer {
    typealias SwiftType = ColumnValue

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ColumnValue {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .null
        
        case 2: return .bool(v: try FfiConverterBool.read(from: &buf)
        )
        
        case 3: return .int8(v: try FfiConverterInt8.read(from: &buf)
        )
        
        case 4: return .int16(v: try FfiConverterInt16.read(from: &buf)
        )
        
        case 5: return .int32(v: try FfiConverterInt32.read(from: &buf)
        )
        
        case 6: return .int64(v: try FfiConverterInt64.read(from: &buf)
        )
        
        case 7: return .uInt8(v: try FfiConverterUInt8.read(from: &buf)
        )
        
        case 8: return .uInt16(v: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 9: return .uInt32(v: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 10: return .uInt64(v: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 11: return .float16(v: try FfiConverterFloat.read(from: &buf)
        )
        
        case 12: return .float32(v: try FfiConverterFloat.read(from: &buf)
        )
        
        case 13: return .float64(v: try FfiConverterDouble.read(from: &buf)
        )
        
        case 14: return .bytes(v: try FfiConverterData.read(from: &buf)
        )
        
        case 15: return .utf8(v: try FfiConverterString.read(from: &buf)
        )
        
        case 16: return .list(items: try FfiConverterSequenceTypeColumnValue.read(from: &buf)
        )
        
        case 17: return .`struct`(fields: try FfiConverterSequenceTypeColumnValue.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ColumnValue, into buf: inout [UInt8]) {
        switch value {
        
        
        case .null:
            writeInt(&buf, Int32(1))
        
        
        case let .bool(v):
            writeInt(&buf, Int32(2))
            FfiConverterBool.write(v, into: &buf)
            
        
        case let .int8(v):
            writeInt(&buf, Int32(3))
            FfiConverterInt8.write(v, into: &buf)
            
        
        case let .int16(v):
            writeInt(&buf, Int32(4))
            FfiConverterInt16.write(v, into: &buf)
            
        
        case let .int32(v):
            writeInt(&buf, Int32(5))
            FfiConverterInt32.write(v, into: &buf)
            
        
        case let .int64(v):
            writeInt(&buf, Int32(6))
            FfiConverterInt64.write(v, into: &buf)
            
        
        case let .uInt8(v):
            writeInt(&buf, Int32(7))
            FfiConverterUInt8.write(v, into: &buf)
            
        
        case let .uInt16(v):
            writeInt(&buf, Int32(8))
            FfiConverterUInt16.write(v, into: &buf)
            
        
        case let .uInt32(v):
            writeInt(&buf, Int32(9))
            FfiConverterUInt32.write(v, into: &buf)
            
        
        case let .uInt64(v):
            writeInt(&buf, Int32(10))
            FfiConverterUInt64.write(v, into: &buf)
            
        
        case let .float16(v):
            writeInt(&buf, Int32(11))
            FfiConverterFloat.write(v, into: &buf)
            
        
        case let .float32(v):
            writeInt(&buf, Int32(12))
            FfiConverterFloat.write(v, into: &buf)
            
        
        case let .float64(v):
            writeInt(&buf, Int32(13))
            FfiConverterDouble.write(v, into: &buf)
            
        
        case let .bytes(v):
            writeInt(&buf, Int32(14))
            FfiConverterData.write(v, into: &buf)
            
        
        case let .utf8(v):
            writeInt(&buf, Int32(15))
            FfiConverterString.write(v, into: &buf)
            
        
        case let .list(items):
            writeInt(&buf, Int32(16))
            FfiConverterSequenceTypeColumnValue.write(items, into: &buf)
            
        
        case let .`struct`(fields):
            writeInt(&buf, Int32(17))
            FfiConverterSequenceTypeColumnValue.write(fields, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColumnValue_lift(_ buf: RustBuffer) throws -> ColumnValue {
    return try FfiConverterTypeColumnValue.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColumnValue_lower(_ value: ColumnValue) -> RustBuffer {
    return FfiConverterTypeColumnValue.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Compression: Equatable, Hashable {
    
    case none
    case snappy
    case lz4
    case gzip(level: UInt8
    )
    case zstd(level: UInt8
    )
    case brotli(level: UInt8
    )





}

#if compiler(>=6)
extension Compression: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompression: FfiConverterRustBuffer {
    typealias SwiftType = Compression

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Compression {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .none
        
        case 2: return .snappy
        
        case 3: return .lz4
        
        case 4: return .gzip(level: try FfiConverterUInt8.read(from: &buf)
        )
        
        case 5: return .zstd(level: try FfiConverterUInt8.read(from: &buf)
        )
        
        case 6: return .brotli(level: try FfiConverterUInt8.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Compression, into buf: inout [UInt8]) {
        switch value {
        
        
        case .none:
            writeInt(&buf, Int32(1))
        
        
        case .snappy:
            writeInt(&buf, Int32(2))
        
        
        case .lz4:
            writeInt(&buf, Int32(3))
        
        
        case let .gzip(level):
            writeInt(&buf, Int32(4))
            FfiConverterUInt8.write(level, into: &buf)
            
        
        case let .zstd(level):
            writeInt(&buf, Int32(5))
            FfiConverterUInt8.write(level, into: &buf)
            
        
        case let .brotli(level):
            writeInt(&buf, Int32(6))
            FfiConverterUInt8.write(level, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompression_lift(_ buf: RustBuffer) throws -> Compression {
    return try FfiConverterTypeCompression.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompression_lower(_ value: Compression) -> RustBuffer {
    return FfiConverterTypeCompression.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Encoding: Equatable, Hashable {
    
    case plain
    case deltaBinaryPacked
    case deltaLengthByteArray
    case deltaByteArray
    case rleDictionary





}

#if compiler(>=6)
extension Encoding: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncoding: FfiConverterRustBuffer {
    typealias SwiftType = Encoding

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Encoding {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .plain
        
        case 2: return .deltaBinaryPacked
        
        case 3: return .deltaLengthByteArray
        
        case 4: return .deltaByteArray
        
        case 5: return .rleDictionary
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Encoding, into buf: inout [UInt8]) {
        switch value {
        
        
        case .plain:
            writeInt(&buf, Int32(1))
        
        
        case .deltaBinaryPacked:
            writeInt(&buf, Int32(2))
        
        
        case .deltaLengthByteArray:
            writeInt(&buf, Int32(3))
        
        
        case .deltaByteArray:
            writeInt(&buf, Int32(4))
        
        
        case .rleDictionary:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncoding_lift(_ buf: RustBuffer) throws -> Encoding {
    return try FfiConverterTypeEncoding.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncoding_lower(_ value: Encoding) -> RustBuffer {
    return FfiConverterTypeEncoding.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Field schema for Parquet columns.
 *
 * For the `List` variant, `fields` contains exactly one element: the element schema.
 * For the `Struct` variant, `fields` contains the struct's child field schemas.
 * For the `Primitive` variant, `fields` is empty.
 */

public enum FieldSchema: Equatable, Hashable {
    
    case primitive(name: String, type: PrimitiveType, nullable: Bool
    )
    case list(name: String, 
        /**
         * Exactly one element: the list's element schema.
         */fields: [FieldSchema], nullable: Bool
    )
    case `struct`(name: String, fields: [FieldSchema], nullable: Bool
    )
    /**
     * A Parquet MAP column.  `fields` contains exactly two elements: `[0]` is
     * the key schema and `[1]` is the value schema (mirrors `List` convention).
     */
    case map(name: String, fields: [FieldSchema], nullable: Bool
    )





}

#if compiler(>=6)
extension FieldSchema: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFieldSchema: FfiConverterRustBuffer {
    typealias SwiftType = FieldSchema

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FieldSchema {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .primitive(name: try FfiConverterString.read(from: &buf), type: try FfiConverterTypePrimitiveType.read(from: &buf), nullable: try FfiConverterBool.read(from: &buf)
        )
        
        case 2: return .list(name: try FfiConverterString.read(from: &buf), fields: try FfiConverterSequenceTypeFieldSchema.read(from: &buf), nullable: try FfiConverterBool.read(from: &buf)
        )
        
        case 3: return .`struct`(name: try FfiConverterString.read(from: &buf), fields: try FfiConverterSequenceTypeFieldSchema.read(from: &buf), nullable: try FfiConverterBool.read(from: &buf)
        )
        
        case 4: return .map(name: try FfiConverterString.read(from: &buf), fields: try FfiConverterSequenceTypeFieldSchema.read(from: &buf), nullable: try FfiConverterBool.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FieldSchema, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .primitive(name,type,nullable):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(name, into: &buf)
            FfiConverterTypePrimitiveType.write(type, into: &buf)
            FfiConverterBool.write(nullable, into: &buf)
            
        
        case let .list(name,fields,nullable):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(name, into: &buf)
            FfiConverterSequenceTypeFieldSchema.write(fields, into: &buf)
            FfiConverterBool.write(nullable, into: &buf)
            
        
        case let .`struct`(name,fields,nullable):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(name, into: &buf)
            FfiConverterSequenceTypeFieldSchema.write(fields, into: &buf)
            FfiConverterBool.write(nullable, into: &buf)
            
        
        case let .map(name,fields,nullable):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(name, into: &buf)
            FfiConverterSequenceTypeFieldSchema.write(fields, into: &buf)
            FfiConverterBool.write(nullable, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldSchema_lift(_ buf: RustBuffer) throws -> FieldSchema {
    return try FfiConverterTypeFieldSchema.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFieldSchema_lower(_ value: FieldSchema) -> RustBuffer {
    return FfiConverterTypeFieldSchema.lower(value)
}



public enum ParquetError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Io(msg: String
    )
    case Schema(msg: String
    )
    case TypeMismatch(msg: String
    )
    case InvalidFile(msg: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension ParquetError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParquetError: FfiConverterRustBuffer {
    typealias SwiftType = ParquetError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParquetError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Io(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Schema(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .TypeMismatch(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidFile(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ParquetError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Io(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Schema(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .TypeMismatch(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidFile(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParquetError_lift(_ buf: RustBuffer) throws -> ParquetError {
    return try FfiConverterTypeParquetError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParquetError_lower(_ value: ParquetError) -> RustBuffer {
    return FfiConverterTypeParquetError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum PrimitiveType: Equatable, Hashable {
    
    case bool
    case int8
    case int16
    case int32
    case int64
    case uInt8
    case uInt16
    case uInt32
    case uInt64
    case float32
    case float64
    case utf8
    case bytes
    case date32
    case timeMs
    case timeUs
    case timeNs
    case timestampMs
    case timestampUs
    case timestampNs
    case timestampMsUtc
    case timestampUsUtc
    case timestampNsUtc
    case durationNs
    /**
     * Parquet INTERVAL: FIXED_LEN_BYTE_ARRAY(12) encoding months (u32), days (u32),
     * milliseconds (u32) in little-endian order.  Mapped to Arrow
     * `Interval(MonthDayNano)` with millis converted to nanoseconds.
     */
    case interval
    case float16
    case fixedBytes(size: UInt32
    )
    case decimal128(precision: UInt8, scale: UInt8
    )





}

#if compiler(>=6)
extension PrimitiveType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrimitiveType: FfiConverterRustBuffer {
    typealias SwiftType = PrimitiveType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrimitiveType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bool
        
        case 2: return .int8
        
        case 3: return .int16
        
        case 4: return .int32
        
        case 5: return .int64
        
        case 6: return .uInt8
        
        case 7: return .uInt16
        
        case 8: return .uInt32
        
        case 9: return .uInt64
        
        case 10: return .float32
        
        case 11: return .float64
        
        case 12: return .utf8
        
        case 13: return .bytes
        
        case 14: return .date32
        
        case 15: return .timeMs
        
        case 16: return .timeUs
        
        case 17: return .timeNs
        
        case 18: return .timestampMs
        
        case 19: return .timestampUs
        
        case 20: return .timestampNs
        
        case 21: return .timestampMsUtc
        
        case 22: return .timestampUsUtc
        
        case 23: return .timestampNsUtc
        
        case 24: return .durationNs
        
        case 25: return .interval
        
        case 26: return .float16
        
        case 27: return .fixedBytes(size: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 28: return .decimal128(precision: try FfiConverterUInt8.read(from: &buf), scale: try FfiConverterUInt8.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PrimitiveType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .bool:
            writeInt(&buf, Int32(1))
        
        
        case .int8:
            writeInt(&buf, Int32(2))
        
        
        case .int16:
            writeInt(&buf, Int32(3))
        
        
        case .int32:
            writeInt(&buf, Int32(4))
        
        
        case .int64:
            writeInt(&buf, Int32(5))
        
        
        case .uInt8:
            writeInt(&buf, Int32(6))
        
        
        case .uInt16:
            writeInt(&buf, Int32(7))
        
        
        case .uInt32:
            writeInt(&buf, Int32(8))
        
        
        case .uInt64:
            writeInt(&buf, Int32(9))
        
        
        case .float32:
            writeInt(&buf, Int32(10))
        
        
        case .float64:
            writeInt(&buf, Int32(11))
        
        
        case .utf8:
            writeInt(&buf, Int32(12))
        
        
        case .bytes:
            writeInt(&buf, Int32(13))
        
        
        case .date32:
            writeInt(&buf, Int32(14))
        
        
        case .timeMs:
            writeInt(&buf, Int32(15))
        
        
        case .timeUs:
            writeInt(&buf, Int32(16))
        
        
        case .timeNs:
            writeInt(&buf, Int32(17))
        
        
        case .timestampMs:
            writeInt(&buf, Int32(18))
        
        
        case .timestampUs:
            writeInt(&buf, Int32(19))
        
        
        case .timestampNs:
            writeInt(&buf, Int32(20))
        
        
        case .timestampMsUtc:
            writeInt(&buf, Int32(21))
        
        
        case .timestampUsUtc:
            writeInt(&buf, Int32(22))
        
        
        case .timestampNsUtc:
            writeInt(&buf, Int32(23))
        
        
        case .durationNs:
            writeInt(&buf, Int32(24))
        
        
        case .interval:
            writeInt(&buf, Int32(25))
        
        
        case .float16:
            writeInt(&buf, Int32(26))
        
        
        case let .fixedBytes(size):
            writeInt(&buf, Int32(27))
            FfiConverterUInt32.write(size, into: &buf)
            
        
        case let .decimal128(precision,scale):
            writeInt(&buf, Int32(28))
            FfiConverterUInt8.write(precision, into: &buf)
            FfiConverterUInt8.write(scale, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrimitiveType_lift(_ buf: RustBuffer) throws -> PrimitiveType {
    return try FfiConverterTypePrimitiveType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrimitiveType_lower(_ value: PrimitiveType) -> RustBuffer {
    return FfiConverterTypePrimitiveType.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCompression: FfiConverterRustBuffer {
    typealias SwiftType = Compression?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCompression.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCompression.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeEncoding: FfiConverterRustBuffer {
    typealias SwiftType = Encoding?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeEncoding.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeEncoding.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceTypeColumnValue: FfiConverterRustBuffer {
    typealias SwiftType = [ColumnValue]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceTypeColumnValue.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceTypeColumnValue.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeColumnConfig: FfiConverterRustBuffer {
    typealias SwiftType = [ColumnConfig]

    public static func write(_ value: [ColumnConfig], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeColumnConfig.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ColumnConfig] {
        let len: Int32 = try readInt(&buf)
        var seq = [ColumnConfig]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeColumnConfig.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeColumnValue: FfiConverterRustBuffer {
    typealias SwiftType = [ColumnValue]

    public static func write(_ value: [ColumnValue], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeColumnValue.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ColumnValue] {
        let len: Int32 = try readInt(&buf)
        var seq = [ColumnValue]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeColumnValue.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFieldSchema: FfiConverterRustBuffer {
    typealias SwiftType = [FieldSchema]

    public static func write(_ value: [FieldSchema], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFieldSchema.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FieldSchema] {
        let len: Int32 = try readInt(&buf)
        var seq = [FieldSchema]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFieldSchema.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_parquet_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_parquet_swift_checksum_method_readerhandle_close() != 24972) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_parquet_swift_checksum_method_readerhandle_read_row() != 18337) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_parquet_swift_checksum_method_readerhandle_schema() != 15662) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_parquet_swift_checksum_method_writerhandle_append_row() != 19841) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_parquet_swift_checksum_method_writerhandle_close() != 48050) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_parquet_swift_checksum_constructor_readerhandle_new() != 8918) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_parquet_swift_checksum_constructor_readerhandle_new_projected() != 55023) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_parquet_swift_checksum_constructor_writerhandle_new() != 41269) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureParquetSwiftInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all