#!/usr/bin/env bash
set -euo pipefail

swift package --allow-writing-to-directory ./Docs \
    generate-documentation --target ParquetKit --output-path ./Docs \
    --transform-for-static-hosting --hosting-base-path ParquetKit